### PR TITLE
fixed gulp tasks with browserify

### PR DESCRIPTION
**Pull request by mkondel**
The only task I was able to do was 'dev' and 'test', but 'default' was breaking on the browserify part:

```js
[21:19:45] Using gulpfile ~~~~~~~~~~/synaptic/gulpfile.js
[21:19:45] Starting 'default'...

_stream_readable.js:601
    var written = dest.write(chunk);
                       ^
TypeError: Object #<Readable> has no method 'write'
    at write (_stream_readable.js:601:24)
    at flow (_stream_readable.js:610:7)
    at _stream_readable.js:578:7
    at process._tickDomainCallback (node.js:463:13)
```

So then I found [Browserify + Uglify with sourcemaps](https://github.com/gulpjs/gulp/blob/4d35560d9e2e992037886897c671518cfe49fd7f/docs/recipes/browserify-uglify-sourcemap.md).  Now can run 'default', 'debug', 'test', 'dev', and the tasks all work on my env.

### CODE REVIEW

**Comment by mkondel** [comment]
Hmm, something that only became apparent to me now, but 'gulp test' does ```synaptic = require('../src/synaptic');```.  Would it be possible to use the built version from the 'dist' dir for this instead?

**Comment by cazala** [comment]
we could point the require to 'dist/synaptic', but then we should also point the [entry point](https://github.com/cazala/synaptic/blob/master/package.json#L5) in `package.json` to that file, so that's going to be the one used when installing the module in node as well.

**Comment by mkondel** [comment]
I can try that.  However, if I simply take the js file produced by my gulp code, I cannot use it in node.  It's that error from my post just above:
```js
synaptic = require('./synaptic.js')
ReferenceError: synaptic is not defined
    at Object.<anonymous> (~~~~~~~~~~~~~~~~~~~~~~~~/synaptic/dist/synaptic.js:54:2752)
    at Module._compile (module.js:456:26)
.............
```
This is from /dist/ and runing node in there.  Am I just doing something wrong with node?

**Comment by cazala** [comment]
mmh I just modified my local gulpfile in the same way you did there and I get the same error. I tried removing the globals but still, calling `require('./dist/synaptic')` returns an empty object, while requiring `./src/synaptic` works fine. I think we should leave the tests and `package.json` pointing to `./src/synaptic`, and leave the browserified version just for the browser, using `./dist/synaptic`

**Comment by cazala** [comment]
The only change I would suggest before merging this PR would be changing the [versions of the dependencies](https://github.com/cazala/synaptic/blob/master/package.json#L10-L16) from `*` to the actual versions:

```
    "browserify": "^10.1.3",
    "gulp": "^3.8.11",
    "gulp-insert": "^0.4.0",
    "gulp-mocha": "^2.0.1",
    "gulp-sourcemaps": "^1.5.2",
    "gulp-uglify": "^1.2.0",
    "gulp-util": "^3.0.4",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0"
```

because I think this is the reason why gulp wasn't working for you (all the tasks worked for me), we probably had different versions of gulp or some plugin, if we target the specific versions of the dependencies we'll make sure that this will work for everyone else who downloads synaptic later.

**Comment by mkondel** [comment]
There are now 2 files in the repo under ./dist/: *synaptic.js* and *synaptic.min.js*.

Gulp tasks now:
- **default**: readable code, no source maps, produces ./dist/synaptic.js
- **min**: not readable, but small, no source maps, produces ./dist/synaptic.min.js
- **debug**: same as 'default', but add source maps, produces the same filename ./dist/synaptic.js
- **dev**, **test**: work like before

All these gulp tasks only produce browser versions.  To use this library in node, you would have to install it with npm, is my understanding this correct?

**Comment by cazala** [comment]
great!

**Pull request merged**
