### PR TITLE
Parallel/multi core processing

### PR DESCRIPTION
**Pull request by shamoons**
@cazala added a test for the network. regardless of the parallelization, I think a test is helpful to have

### CODE REVIEW

**Comment by cazala** [comment]
@shamoons Travis CI [failed to build](https://travis-ci.org/cazala/synaptic/builds/54620302), apparently paralleljs is missing, is it included as a dependency?

**Comment by shamoons** [comment]
It is a dependency. Rather, it will be once I finish the worker splitting. This is just to add a test for the network to make sure I don't break anything later. 

What's the best way to include it as a dependency?

**Comment by cazala** [comment]
you could try to add it in the `package.json` under `devDependencies`, it should get installed when the CI runs `npm install` at [this point](https://travis-ci.org/cazala/synaptic/builds/54620302#L94)

**Comment by lililya** [comment]
w

**Pull request closed without merging**
