### PR TITLE
Rate callback

### PR DESCRIPTION
**Pull request by bobalazek**
It would be nice to be able to set a callback for the rate.

### CODE REVIEW

**Comment by cazala** [comment]
Nice!

**Comment by menduz** [comment]
LGTM, please build the dist files and then we are able to merge it. @bobalazek

**Comment by menduz** [comment]
(Y)

**Comment by menduz** [comment]
Could you add a test? @bobalazek

**Comment by bobalazek** [comment]
Ah yeah, sure, totally forgot. Will do ao shortly!

**Pull request merged**
